### ISSUE TITLE
Necessary improvements before alpha-release

### ISSUE THREAD

**Issue by michaelgruenstaeudl** [michaelgruenstaeudl/PlastomeBurstAndAlign#24]
- [x] **Moving "scary" warning messages to the verbose option**

The following warning message pair (which addresses the same issue) is only one of hundreds of similar warning messages that occur when running `python test_script_cds.py` for benchmarking dataset 2. While these specific warning messages are entirely correct and helpful to a developer, they would scare away every regular biology user and could be confused as errors of our software rather than what they really are: issues with the underlying GenBank flatfiles.

```
2024-07-18 15:48:49 [WARNING] Inconsistent lengths for rps2_KY636008, ungapped protein 94, tripled 282 vs ungapped nucleotide 306.
Protein:     GTLIKRKQEFILVMVLRNGILKWPLTFRQSVKVLILISLERLVFXXXXXXXXXXXXXXXX
             ....!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!.!!!!!!!!!............
Translation: GTLIXKRXXKQEFILVMVLRNGILKWPLTFRQSVKVLILXISLERLVFXXXXXXXXXXXX

Protein:     XXXXXVPKKEQQIHQLQGLVVIMLIKSGSVVCRI
             .....!!!!!!!!!.!!!!!!!!!!!!!!!!!!!
Translation: XXXXXXXXXVPKKEQQIXXHQLQXGLVVIMLIKSGSVVCXRI

2024-07-18 15:48:49 [WARNING] Translation check failed for rps2_KY636008
```

Hence, could you please implement a "verbose" option among the command-line parameters that is not activated by default and during which these specific warnings are displayed. 

The same goes for `self._print_align()` of `_insert_at_index`, which also produces "scary" yet correct warnings on the underlying data and which need to be quarantined behind a verbose option for regular biology users.

That way, I hope, we satisfy the demands of both regular users as well as potential developers who which to reuse our code.

---

- [x] **Trans-spliced genes need special handling in the code**

In GenBank flatfiles, trans-spliced genes are always listed at the very beginning of the FEATURES section and, thus, out of their natural order of occurrence in the genome. They are marked by the feature tag `/trans_splicing` and always exhibit compound locations. The gene `rps12` is basically the only trans-spliced gene to be encountered among plastid genomes (all other trans-spliced genes are extremely rare and, thus, negligible.)

In the current code, class `CompoundSplitting` splits and, where necessary, repositions the exons of any compound feature, but in practice it only operates on the trans-spliced genes because these are the only ones that are out of their natural gene order. To avoid any unintended behavior via class `CompoundSplitting` (which otherwise is quite nice!), the class should probably be split into a general section (that operates on all genes with compound exon locations) and a trans-spliced section (that only operates on trans-spliced genes, which can/should be identified via their feature tag `/trans_splicing` ).

---

- [x] **Improved feedback to user why a sequence object was not extracted**

When extracting and aligning intergenic spacers (i.e., when running `python test_script_igs.py`), the code currently performs the following evaluation:
```    
def add_feature(self, feature: Union['GeneFeature', 'IntronFeature', 'ProteinFeature', 'IntergenicFeature']):
    if feature.seq_obj is None:
        log.warning(f"{feature.seq_name} does not have an unambiguous reading frame. Skipping this feature.")
            return
```
The resulting warning message (e.g., `psbD_psbC_NC_034823 does not have a clear reading frame. Skipping this feature.`) cannot be correct for either an intron or an intergenic spacer, as neither have a reading frame (they are, by definition, non-coding). Hence, we need to customize the warning message somehow, even though that is probably not easy.  (Maybe we should move those warning messages to the individual classes `GeneFeature`, `IntronFeature`, and `IntergenicFeature` ?!)

At the same time, there is something fishy going on, as an error message such as `psbD_psbC_NC_034823 does not have a clear reading frame. Skipping this feature.` should probably have triggered the exception clause in `_set_seq_obj` of class `IntergenicFeature` yet hasn't.

Finally, it would be great if we could parse `{feature.seq_name}` such that the warning messages read something like `Intergenic spacer 'psbD_psbC' in NC_034823 is being skipped due to ...` or `Gene 'psbD' in NC_034823 is being skipped due to ...`

---

- [x] **Letter-case issue 1: Possibility of artificially high number of IGS that do not reach the minimum number of taxa defined**

For benchmarking dataset 1, there are 230 cases of intergenic spacers that were removed from the dataset for not reaching the minimum number of taxa defined. While theoretically possible, it seems an excessive number to me, and I suspect that a portion of these cases is rather due to an issue with case-letters (or an underscore instead of a dash) in the region names, especially for the tRNA genes, which by default have the following format: `[name of tRNA][dash][three letter codon it is represented by]`.
For example, the official way to write the tRNA for the amino acid Leucine is `trnL-UAA`.

The following two cases of datasets that do not reach the minimum number of taxa defined are for gene "trnL-UAA" and may be due to the fact that a few GenBank records have incorrect letter-cases or an underscore instead of a dash:

```
2024-07-18 14:06:39 [INFO]     removing trnT_ugu_trnL_uaa for not reaching the minimum number of taxa defined
2024-07-18 14:06:39 [INFO]     removing trnL_uaa_trnF_gaa for not reaching the minimum number of taxa defined
```
```
grep "trnL" *.gb | awk '{print$2}' | sort -u 
/gene="trnL_caa"
/gene="trnL-CAA"
/gene="trnL_CAA"
/gene="trnL-TAG"
/gene="trnL_uaa"
/gene="trnL-UAA"
/gene="trnL_uag"
/gene="trnL-UAG"
```

Can you think of a way to amend the code such that the tRNA names receive the correct letter casing **during or shortly after the parsing of the sequence records**. That would help to decrease the number of regions that do not reach the minimum number of taxa defined.

---

- [x] **Letter-case issue 2: Minor bug**

The following warning message occurs when running `python test_script_cds.py` for benchmarking dataset 2. I suspect that it has something to do with the letter-case handling when parsing the input files.

```
2024-07-18 15:54:52 [WARNING] Unable to conduct back-translation of `PsbB`. Error message: No records found in handle.
2024-07-18 15:55:14 [WARNING] Unable to convert alignment of `psbB` from FASTA to NEXUS.
Error message: [Errno 2] No such file or directory: 'benchmarking2/output_CDS/nucl_psbB.aligned.fasta'
2024-07-18 15:55:29 [WARNING] Unable to convert alignment of `PsbB` from FASTA to NEXUS.
Error message: [Errno 2] No such file or directory: 'benchmarking2/output_CDS/nucl_PsbB.aligned.fasta'
```

Could you please adjust the software code so that capitalized genes (e.g., 'PsbB') are automatically understood to have the official gene name format, which is three lower-case letters, followed by one upper-case letter (i.e., 'psbB' in the example).

Maybe you could insert an try-except clause when dealing with the conversions from FASTA to NEXUS. The current warning message (e.g., `[WARNING] Unable to convert alignment of `psbB` from FASTA to NEXUS.`) is sufficient for such cases, I believe; the subsequent error message (e.g., `Error message: [Errno 2] No such file or directory: 'benchmarking2/output_CDS/nucl_psbB.aligned.fasta'`) seems excessive.

---

- [x] **Heads-up regarding packaging PlastomeBurstAndAlign as a PyPI package**

Once the above changes have been made, we can think of subdividing the script into proper module files and packaging everything as a PyPI package. It is easy to do, and we can follow [this example](https://github.com/michaelgruenstaeudl/annonex2embl), which worked well.

---

- [x] **Adding a native Python aligner next to MAFFT**

Journal reviewers are not always computationally adept. To avoid having our future manuscript shot down because of an inability of the reviewer to install MAFFT on their system, it may be prudent to include an all-Python option for the multiple sequence alignment that is installed automatically when installing PlastomeBurstAndAlign (which will be a PyPI package once it is ready and, thus, easily installable). An all-Python tool for multiple sequence alignment is [Cogent3](https://github.com/cogent3/cogent3). Feel free to look into adding Cogent3 as an alternative to MAFFT.

**Comment by alephnull7** [comment]
Using your insight into genetic naming conventions I have been able to reduce the number of discarded intergenic spacers in benchmark 2 by about 25% compared to the existing approach. When investigating common properties of the remaining discarded features, it does look like inconsistent naming of tRNA genes is a major culprit. What I mean by this is it is not uncommon for these genes to appear in one of four ways: consisting of just the four character gene name, additionally including the anticodon, additionally including the amino acid, and additionally including both the amino acid and anticodon. From a quick read about tRNA genes, I would guess that any of these forms would likely refer to the same gene, especially given the existing and intended use case of the software. Removing any qualifier from tRNA genes results in an additional reduction in the number of discarded genes by about 35%. Note that the original 25% reduction includes standardizing the case of amino acid abbreviations and anticodon sequences, so this additional reduction is just for their elimination. Let me know if it would be prudent to add the tRNA qualifier removal to the gene name-cleaning process.

**Comment by michaelgruenstaeudl** [comment]
> Using your insight into genetic naming conventions I have been able to reduce the number of discarded intergenic spacers in benchmark 2 by about 25% compared to the existing approach. When investigating common properties of the remaining discarded features, it does look like inconsistent naming of tRNA genes is a major culprit. What I mean by this is it is not uncommon for these genes to appear in one of four ways: consisting of just the four character gene name, additionally including the anticodon, additionally including the amino acid, and additionally including both the amino acid and anticodon. From a quick read about tRNA genes, I would guess that any of these forms would likely refer to the same gene, especially given the existing and intended use case of the software. Removing any qualifier from tRNA genes results in an additional reduction in the number of discarded genes by about 35%. Note that the original 25% reduction includes standardizing the case of amino acid abbreviations and anticodon sequences, so this additional reduction is just for their elimination. Let me know if it would be prudent to add the tRNA qualifier removal to the gene name-cleaning process.

Excellent diagnosis of the issue and wonderful coding work! Yes, tRNA gene names are a major culprit when searching for and collecting homologous (i.e., comparable) genes. Your approach is miles better than what has been achieved in other software. However, we need to roll back the option to exclude qualifiers completely (as this is too risky in the face of future reviewer criticism) and make only the gene name standardization process the default behavior of the software. I have explained the issue in more detail in [issue #27](https://github.com/michaelgruenstaeudl/PlastomeBurstAndAlign/issues/27).
