### ISSUE TITLE
Towards a manuscript on PlastomeBurstAndAlign #1

### ISSUE THREAD

**Issue by michaelgruenstaeudl** [michaelgruenstaeudl/PlastomeBurstAndAlign#26]
- [x] **Description/illustration of the compound location feature handler**
Your extended code of handling compound features looks great but it is too complex for me to comprehend without a written description or flowchart. More importantly, a brief description and a flowchart will be needed for the manuscript anyways. Based on your sentences above, could you please draft a paragraph (5-6 sentences only) as well as a flowchart that explain what the class `CompoundSplitting` does.

- [x] **Renaming of some variables in class 'PlastidDict'**
In class `PlastidDict`, the variable or function names `plastome_nucs`, `nuc_name`, and `_is_nuc` may not be ideally chosen, because all features in a DNA sequence will be nucleotides. Unless there is a good reason to name them "nuc", could they renamed to something like "feature" (i.e., `plastome_features`, `feature_name`, and `_is_feature).

**Comment by alephnull7** [comment]
I saw your comment about variable naming and have updated the names you referenced and have updated other variable names to improve their meaning.

In my effort to rework the script into a package, I spent some time commenting on aspects of the code intended to be utilized by an end user. Part of that involved adding a description of the processes used in the `ExonSpliceHandler` class, which was renamed from `CompoundSplitting` to better describe what it does. Below I will try to rework what I detailed there:

The gene list is iterated over and cis-spliced genes are merged in place as they occur within the source GenBank file (no repositioning of the annotations). During this process, compound location annotations qualified as trans-spliced or known to be trans-spliced, namely rps12, are removed from the list of gene features, and retained in a separate list. These trans-spliced genes are split into simple location features, with each split resulting in a simple location feature for each contiguous location of the compound location. We then determine the expected location of each of these simple features by comparing its end location with the end locations of the features in the gene list. If the expected location has no overlap with the proceeding and succeeding genes, and the feature is a different gene from those two, it is directly inserted into that expected location. Alternatively, if the expected location of the feature results in a flanking gene (strictly adjacent or overlapping) being the same as the gene to be inserted they are merged, possibly with both the proceeding and succeeding gene.

I will work on a diagram to detail how this is accomplished in the implementation.

**Comment by michaelgruenstaeudl** [comment]
- [ ] Can you please change "using included MAFFT for alignment" to "using the MAFFT executable that ships with the package for alignment".

**Comment by michaelgruenstaeudl** [comment]
> In my effort to rework the script into a package, I spent some time commenting on aspects of the code intended to be utilized by an end user. Part of that involved adding a description of the processes used in the `ExonSpliceHandler` class, which was renamed from `CompoundSplitting` to better describe what it does. Below I will try to rework what I detailed there:
> 
> The gene list is iterated over and cis-spliced genes are merged in place as they occur within the source GenBank file (no repositioning of the annotations). During this process, compound location annotations qualified as trans-spliced or known to be trans-spliced, namely rps12, are removed from the list of gene features, and retained in a separate list. These trans-spliced genes are split into simple location features, with each split resulting in a simple location feature for each contiguous location of the compound location. We then determine the expected location of each of these simple features by comparing its end location with the end locations of the features in the gene list. If the expected location has no overlap with the proceeding and succeeding genes, and the feature is a different gene from those two, it is directly inserted into that expected location. Alternatively, if the expected location of the feature results in a flanking gene (strictly adjacent or overlapping) being the same as the gene to be inserted they are merged, possibly with both the proceeding and succeeding gene.

Based on your text, I have generated a new paragraph that I believe explains the process to a reader unfamiliar with the computational handling of exons. The text is part of the README of this package and will eventually be used for our manuscript. Please amend the paragraph as you see fit.
